### ISSUE TITLE
Possible to use without username and password

### ISSUE THREAD

**Issue by tvillingett** [ilcato/homebridge-mqttswitch#1]
Almost there for me:
I'm using a local mqtt broker, without username / pw, so I would like for it to be usable without.
Maybe both take care of no "user" parameter and with "" / NULL as user / password.

**Comment by bwired-nl** [comment]
Same here, local no user & pw

**Comment by tvillingett** [comment]
You can use "" as username and password, it works for me. The error I got was from misconfiguring the URL for the broker (#2 issue that I just closed)
