### ISSUE TITLE
[homebridge-mqtt.mqtt] config undefined or null!

### ISSUE THREAD

**Issue by Geeroz** [ilcato/homebridge-mqttswitch#7]
I'm having this issue 'config undefined or null!'
homebridge sill note load

`[10/9/2016, 7:04:52 PM] Loaded config.json with 1 accessories and 0 platforms.
[10/9/2016, 7:04:52 PM] ---
[10/9/2016, 7:04:52 PM] Loading 0 platforms...
[10/9/2016, 7:04:52 PM] Loading 1 accessories...
[10/9/2016, 7:04:52 PM] [MQTT_Test_Switch] Initializing mqttswitch accessory...
Load homebridge-mqtt.mqtt
[10/9/2016, 7:04:52 PM] [homebridge-mqtt.mqtt] config undefined or null!
[10/9/2016, 7:04:52 PM] [homebridge-mqtt.mqtt] storagePath = /home/pi/.homebridge`

here is my config.json

`"accessories": [
        {
                "accessory": "mqttswitch",
                "name": "MQTT_Test_Switch",
                "username": " ",
                "password": " ",
                "url": "mqtt://192.168.1.123",
                "caption": "MQTT_Label",
                "topics":
                {
                        "statusGet":    "switch1status",
                        "statusSet":    "switch1command"
                }
        }
    ],

```
"platforms": [
]`
```

**Comment by Geeroz** [comment]
I figure it out. Kind of stupid. This error has nothing to do with mqttswitch. It's actually from mqtt plugin that I previously install but didn't want to use it. Remove that plugin now everything is fine.

**Comment by boejoyd** [comment]
What plugin was that.  I'm getting the same error.
