### ISSUE TITLE
How to send "on" or "off" command

### ISSUE THREAD

**Issue by DJ-Q** [ilcato/homebridge-mqttswitch#9]
I have this set up with a sonoff device but I can only get "off" to work. When I flick the switch to on or off position in Home app it only ever send the off command. My sonoff is expecting cmnd/sonoff/power on and cmnd/sonoff/power off as topic and message. This works fine from command line mosquitto_pub but I can't for the life of me figure out the correct syntax in my config.json file to make this happen.  Any ideas?

**Comment by ilcato** [comment]
How do you configure it?

**Comment by DJ-Q** [comment]
Like this

{
"bridge": {
"name": "Homebridge-02",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

```
"platforms": [
],
"accessories": [
{
        "accessory": "mqttswitch",
        "name": "BigLamp",
        "url": "mqtt://127.0.0.1",
                "username": "",
                "password": "",
                "caption": "Big Lamp",
                "topics": {
                        "statusGet": "stat/sonoff/power",
                        "statusSet": "cmnd/sonoff/power",
                        "onValue": "ON",
                        "offValue": "OFF"

                }
}
```

]
}

**Comment by ilcato** [comment]
Just updated plugin to version 0.0.3.
Upgrade and retry.

**Comment by DJ-Q** [comment]
Thank you for the reply, i have updated the plugin to 0.0.3 but it still not working.  it still seems to sending "TRUE" or "FALSE" and not "ON" or "OFF" even though o have set the onvalue and offvalue

**Comment by ilcato** [comment]
Change the config this way:
`
"accessories": [
{
        "accessory": "mqttswitch",
        "name": "BigLamp",
        "url": "mqtt://127.0.0.1",
                "username": "",
                "password": "",
                "caption": "Big Lamp",
                "topics": {
                        "statusGet": "stat/sonoff/power",
                        "statusSet": "cmnd/sonoff/power"
                },
                "onValue": "ON",
                "offValue": "OFF"
}
`

**Comment by DJ-Q** [comment]
How is that different to what I have already?

**Comment by ilcato** [comment]
The onValue and offValue must be outside the parenthesis of the topics field.

**Comment by DJ-Q** [comment]
That worked thank you for your help

**Comment by Hucksleyy91** [comment]
Hey I can’t get this to work
My config:

    {
      "topics" : {
        "statusGet" : "stat/vegtablegardenwater/POWER",
        "statusSet" : "cmnd/vegtablegardenwater/power"
      },
      "accessory" : "mqtt-sprinkler",
      "qos" : "0",
      "caption" : "Garden",
      "integerValue" : "TRUE",
      "onValue" : "ON",
      "offValue" : "OFF",
      "name" : "TEST MANG",
      "url" : "192.168.1.192:1883"
    }

I’ve tried changing everything 

I downloaded an app on my iPhone and I can subscribe to mqtt topic and turn my switch on and off, but I can’t get the mqtt-sprinkler accessory to do it
